# NumPy Basics

In [1]:
import numpy as np

## Array Creation

In [2]:
myarr = np.array([8, 9, 4])
myarr

array([8, 9, 4])

In [3]:
myarr[0]

np.int64(8)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(3,)

In [6]:
myarr.size

3

In [7]:
myarr.ndim

1

## Indexing & Slicing

In [8]:
myarr[1:]  # slice from index 1 to the end

array([9, 4])

In [9]:
myarr[-1]  # negative indexing - last element

np.int64(4)

In [10]:
myarr[::-1]  # reverse the array

array([4, 9, 8])

## NumPy Axis

In [11]:
x = [[1, 2, 3], [4, 5, 6]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ar.sum(axis=0)  # sum down the columns

array([5, 7, 9])

In [13]:
ar.sum(axis=1)  # sum across the rows

array([ 6, 15])

## Conversion from Python Structures



In [14]:
arr3d = np.array([
    [[1, 2, 2], [3, 2, 4]],
    [[6, 7, 2], [8, 9, 4]]
])
arr3d

array([[[1, 2, 2],
        [3, 2, 4]],

       [[6, 7, 2],
        [8, 9, 4]]])

In [15]:
arr3d.size

12

In [16]:
arr3d.shape

(2, 2, 3)

In [17]:
arr3d.ndim

3

## Intrinsic NumPy Array Creation Functions


In [18]:
zeros = np.zeros((4, 2, 3), np.int8)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [19]:
arange_arr = np.arange(13)
arange_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
lin = np.linspace(0, 4, 5)
lin

array([0., 1., 2., 3., 4.])

In [21]:
emp = np.empty((4, 2))  # uninitialized values 
emp

array([[5.16541904e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [22]:
ide = np.identity(3)  # creates an identity matrix
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Reshaping & Flattening

In [23]:
arr = np.arange(45)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [24]:
arr = arr.reshape(3, 15)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [25]:
arr.ravel()  # flattens back to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [26]:
# Combining arrays: concatenate / vstack / hstack
p1 = np.array([1, 2, 3])
p2 = np.array([4, 5, 6])
np.concatenate((p1, p2))

array([1, 2, 3, 4, 5, 6])

In [27]:
np.vstack((p1, p2))  # stack as rows

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.hstack((p1, p2))  # stack side by side

array([1, 2, 3, 4, 5, 6])

## Random Arrays

In [29]:
rand_arr = np.random.rand(2, 3)
rand_arr

array([[0.86135314, 0.66871123, 0.57168714],
       [0.23697038, 0.66038729, 0.98093913]])

## Miscellaneous Functions

In [30]:
arr1 = np.array([[2, 3, 24], [44, 5, 6]])
arr1

array([[ 2,  3, 24],
       [44,  5,  6]])

In [31]:
arr1.argmin()  # index of the smallest element (flattened)

np.int64(0)

In [32]:
arr1.argmax(axis=0)  # index of the largest element along each column

array([1, 1, 0])

In [33]:
arr1.ndim

2

In [34]:
arr1.ravel()

array([ 2,  3, 24, 44,  5,  6])

In [35]:
arr1.reshape(3, 2)

array([[ 2,  3],
       [24, 44],
       [ 5,  6]])

In [36]:
arr1.min(), arr1.max(), arr1.mean()

(np.int64(2), np.int64(44), np.float64(14.0))

## Matrix Operations

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
b = np.array([[11, 22, 13], [14, 15, 16], [17, 18, 19]])
b

array([[11, 22, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [39]:
a + b

array([[12, 24, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [40]:
a - b

array([[-10, -20, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [41]:
a * b  # element-wise multiplication, NOT matrix multiplication

array([[ 11,  44,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [42]:
a / b

array([[0.09090909, 0.09090909, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [43]:
a * a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [44]:
a % b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [46]:
np.where(a < 3)

(array([0, 0]), array([0, 1]))

In [47]:
type(np.where(a < 3))

tuple

In [48]:
np.count_nonzero(a)

np.int64(9)

In [49]:
a.T  # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
a @ b  # true matrix multiplication -- compare with a*b abov

array([[ 90, 106, 102],
       [216, 271, 246],
       [342, 436, 390]])

## Memory & System Info

In [51]:
import sys

In [52]:
n = np.array([1, 2, 3])

In [53]:
p = [1, 2, 3]

In [54]:
sys.getsizeof(1) * len(p)  # usual python size check -- note: hardcodes size of '1' instead of p's actual elements, only safe for small ints

84

In [55]:
n.itemsize * n.size  # numpy item size

24

In [56]:
n.dtype

dtype('int64')

## Meshgrid
converts two 1D arrays into two 2D arrays representing all possible combinations of their values as x-y coordinates.

In [57]:

x = [1, 2]
y = [1, 2, 3]

X, Y = np.meshgrid(x, y)
