In [1]:
import numpy as np 

In [2]:
a = np.random.randint(1,100,15)
a

array([69, 52, 86, 29, 70, 48, 88, 36, 14, 68, 78, 49, 87, 51, 19])

In [3]:
b = np.random.randint(1,100,15).reshape(3,5)
b

array([[50,  1, 53, 11, 43],
       [78, 75, 17, 46, 52],
       [61, 21, 63,  1, 32]])

### sort

In [4]:
np.sort(a)

array([14, 19, 29, 36, 48, 49, 51, 52, 68, 69, 70, 78, 86, 87, 88])

In [5]:
np.sort(b)  # sorting in row 

array([[ 1, 11, 43, 50, 53],
       [17, 46, 52, 75, 78],
       [ 1, 21, 32, 61, 63]])

In [6]:
np.sort(b, axis=0)[::-1]  # sorting column wise and in desending order

array([[78, 75, 63, 46, 52],
       [61, 21, 53, 11, 43],
       [50,  1, 17,  1, 32]])

### append

In [7]:
np.append(a,200)

array([ 69,  52,  86,  29,  70,  48,  88,  36,  14,  68,  78,  49,  87,
        51,  19, 200])

In [8]:
np.append(b, np.ones((b.shape[0], 1)), axis=1) # to append column of ones at the end

array([[50.,  1., 53., 11., 43.,  1.],
       [78., 75., 17., 46., 52.,  1.],
       [61., 21., 63.,  1., 32.,  1.]])

### concatenate

In [9]:
c = np.random.randint(1,100,6).reshape(2,3)
d = np.random.randint(1,100,6).reshape(2,3)

print(c)
print(d)

[[48 51 79]
 [37 96  9]]
[[71 85 31]
 [97 78 11]]


In [10]:
np.concat((c,d),axis=0)

array([[48, 51, 79],
       [37, 96,  9],
       [71, 85, 31],
       [97, 78, 11]])

In [11]:
np.concat((c,d),axis=1)

array([[48, 51, 79, 71, 85, 31],
       [37, 96,  9, 97, 78, 11]])

### unique

In [12]:
e = np.array([1,1,2,3,3,2,13,3,4,42,1,1,2,4])

In [13]:
np.unique(e)

array([ 1,  2,  3,  4, 13, 42])

### Expand dimensions  ( concerting or expanding array dimesions)
used in converstion of row vector and column vector

In [17]:
np.expand_dims(a,axis=0) 

array([[69, 52, 86, 29, 70, 48, 88, 36, 14, 68, 78, 49, 87, 51, 19]])

In [19]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1) 

array([[69],
       [52],
       [86],
       [29],
       [70],
       [48],
       [88],
       [36],
       [14],
       [68],
       [78],
       [49],
       [87],
       [51],
       [19]])

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where
returns the indices of elements in an input array

In [24]:
np.where(a>50)

(array([ 0,  1,  2,  4,  6,  9, 10, 12, 13]),)

In [30]:
# replace all values > 50 to 0 
np.where(a >50 ,0,a)

array([ 0,  0,  0, 29,  0, 48,  0, 36, 14,  0,  0, 49,  0,  0, 19])

In [31]:
np.where(b%2 ==0 , 0 ,b)

array([[ 0,  1, 53, 11, 43],
       [ 0, 75, 17,  0,  0],
       [61, 21, 63,  1,  0]])

### argmax

In [33]:
np.argmax(a)  # returns index of max value

np.int64(6)

In [39]:
np.argmax(b, axis=1)

array([2, 0, 2])

### argmin

In [41]:
np.argmin(a)

np.int64(8)

### np.cumsum 
cumulative sum or running sum

In [47]:
b

array([[50,  1, 53, 11, 43],
       [78, 75, 17, 46, 52],
       [61, 21, 63,  1, 32]])

In [48]:
np.cumsum(b)

array([ 50,  51, 104, 115, 158, 236, 311, 328, 374, 426, 487, 508, 571,
       572, 604])

In [46]:
np.cumsum(b, axis=1)

array([[ 50,  51, 104, 115, 158],
       [ 78, 153, 170, 216, 268],
       [ 61,  82, 145, 146, 178]])

### np.cumprod

In [50]:
np.cumprod(e)

array([      1,       1,       2,       6,      18,      36,     468,
          1404,    5616,  235872,  235872,  235872,  471744, 1886976])

### np.percentile

In [56]:
np.percentile(a,100)  # HIGHEST OR 100TH percentile

np.float64(88.0)

In [58]:
np.percentile(a,50)  # middle

np.float64(52.0)

In [59]:
np.percentile(a,0) # lowesst

np.float64(14.0)

### np.histogram

In [65]:
np.histogram(a, bins=[0,20,30,40,50,60,70,80,100])

(array([2, 1, 1, 2, 2, 2, 2, 3]),
 array([  0,  20,  30,  40,  50,  60,  70,  80, 100]))

### np.corrcoef  
coreelation coefficient

In [68]:
sal = np.array([10000,20000,30000,40000,10000])
exp = np.array([1,2,3,4,2])

np.corrcoef(sal,exp)

array([[1.        , 0.94174191],
       [0.94174191, 1.        ]])


            | salary  | experience                                                     
salary                                                                                                  
experience 

### np.isin()

In [69]:
item = [10,20,30,40,50,60]

In [72]:
np.isin(b,item)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [73]:
b[np.isin(b,item)]

array([50])

### np.flip
reverse the order of array elements 

In [75]:
a

array([69, 52, 86, 29, 70, 48, 88, 36, 14, 68, 78, 49, 87, 51, 19])

In [76]:
np.flip(a)

array([19, 51, 87, 49, 78, 68, 14, 36, 88, 48, 70, 29, 86, 52, 69])

In [77]:
b

array([[50,  1, 53, 11, 43],
       [78, 75, 17, 46, 52],
       [61, 21, 63,  1, 32]])

In [78]:
np.flip(b)

array([[32,  1, 63, 21, 61],
       [52, 46, 17, 75, 78],
       [43, 11, 53,  1, 50]])

In [80]:
np.flip(b , axis=0) # column flip

array([[61, 21, 63,  1, 32],
       [78, 75, 17, 46, 52],
       [50,  1, 53, 11, 43]])

### np.put

In [81]:
a

array([69, 52, 86, 29, 70, 48, 88, 36, 14, 68, 78, 49, 87, 51, 19])

In [82]:
np.put(a,[0,1],[2000,800])

In [83]:
a

array([2000,  800,   86,   29,   70,   48,   88,   36,   14,   68,   78,
         49,   87,   51,   19])

### np.delete

In [88]:
np.delete(a, 2)  # specify index

array([2000,  800,   29,   70,   48,   88,   36,   14,   68,   78,   49,
         87,   51,   19])

In [89]:
np.delete(b, 2) 

array([50,  1, 11, 43, 78, 75, 17, 46, 52, 61, 21, 63,  1, 32])

## Set functions

In [90]:
m = np.array([1,2,3,4,5,6,7])
n = np.array([1,3,5,7,9,11,13])

In [92]:
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 13])

In [93]:
np.intersect1d(m,n)

array([1, 3, 5, 7])

In [94]:
np.setdiff1d(m,n)

array([2, 4, 6])

In [95]:
np.setxor1d(m,n)

array([ 2,  4,  6,  9, 11, 13])

In [103]:
np.clip(a,a_min=2,a_max=76)  # limitng value in range

array([76, 76, 76, 29, 70, 48, 76, 36, 14, 68, 76, 49, 76, 51, 19])

### miscellaneous functions

In [109]:
a

array([2000,  800,   86,   29,   70,   48,   88,   36,   14,   68,   78,
         49,   87,   51,   19])

In [110]:
b

array([[50,  1, 53, 11, 43],
       [78, 75, 17, 46, 52],
       [61, 21, 63,  1, 32]])

In [106]:
np.swapaxes(b, 0, 1)
# swaps between axes

array([[50, 78, 61],
       [ 1, 75, 21],
       [53, 17, 63],
       [11, 46,  1],
       [43, 52, 32]])

In [113]:
np.random.uniform(0, 10, 5)
# generates 5 random numbers between 0 and 10

array([6.57383739, 4.29489331, 9.71702095, 1.69397919, 6.33638434])

In [114]:
a

array([2000,  800,   86,   29,   70,   48,   88,   36,   14,   68,   78,
         49,   87,   51,   19])

In [115]:
np.count_nonzero(a)
# counts the number of non-zero elements

np.int64(15)

In [116]:
np.repeat(a, 3)
# repeats each element 3 times

array([2000, 2000, 2000,  800,  800,  800,   86,   86,   86,   29,   29,
         29,   70,   70,   70,   48,   48,   48,   88,   88,   88,   36,
         36,   36,   14,   14,   14,   68,   68,   68,   78,   78,   78,
         49,   49,   49,   87,   87,   87,   51,   51,   51,   19,   19,
         19])